/**
 * 20 bedtime stories: 5 per topic. Simple words for reading aloud (title + moral are spoken too).
 */
(function () {
  function story(title, paragraphs, moral) {
    return { title, paragraphs, moral };
  }

  window.PRELOADED_STORIES_BY_TOPIC = {
    unicorn: [
      story("The Horn That Remembered Kindness", [
        "Long ago, beside a river full of smooth stones, lived a young unicorn named Seren. Her coat was the soft gray of morning fog, and her horn caught light the way a candle catches a careful hand. Seren’s mother told her that a unicorn horn remembers every kind thing the unicorn does, keeping those memories like a quiet diary.",
        "One night the sky turned pink, soft purple, and gold. The sun was going to sleep. Anyone who loves stories about kind animals would have liked the smell of that night air. It smelled like clover, cool water, and a little bit of honey.",
        "Seren was walking home. She had helped her mother carry reeds for birds who build nests. The path went through birch trees. The leaves made a tiny bell sound. Then Seren heard a small, scared chirp again and again.",
        "She followed the sound to a hollow log. Inside, on soft moss, sat a little finch. One wing hung down. The bird looked hurt, but it was trying to be brave. Seren did not run up fast. Scared animals need time to see that help is safe.",
        "Seren asked, May I sit near you? She used the same soft voice she used for a sleepy baby horse. The finch blinked. Seren lay down slowly on the grass. Her horn glowed a little bit, like a small night light for the moss.",
        "For a long time Seren just breathed. She told the finch simple true things. The river will still be here tomorrow. Stars will come out. Moss is soft if you rest on it. The finch’s chirps slowed down. The bird still hurt, but it felt a little calmer.",
        "When the finch hopped closer, Seren touched the hurt wing with her horn. There was no big flash. There was only warm, steady light, like hands cupped around a candle. The finch stretched. The wing sat straighter. The feathers looked happier.",
        "The finch sang a test note, then sang again with joy. Seren laughed. Her horn glowed a little brighter with a new good memory. The finch flew to a branch, then circled Seren’s head three times, like a thank-you dance. Then it flew toward the moon path on the water.",
        "News spreads fast when animals listen well. The next night, a polite line waited for Seren. A mouse had a splinter. A turtle lost a sunny rock it loved. A shy fox cub wanted courage to say hello to the night. Seren helped each one the same way. First she waited. Then she told the truth. Then she used a tiny bit of horn light.",
        "Kindness can still make you tired. On the third night Seren felt heavy. Her horn’s glow went soft and pulsing. Her mother found her by the river. Seren stared at the water like she did not know herself.",
        "Seren whispered, What if I run out? What if my horn forgets how to warm? Her mother touched her horn to Seren’s horn. She said, A horn does not run out. It grows deeper. But bodies need rest. Even stars rest behind clouds.",
        "That night Seren slept under cozy quilts. She dreamed of a child under blankets, half asleep and smiling. Help can be quiet, the dream said. In the dream, the child put a hand on her chest and felt a small warm spot, like borrowed unicorn light.",
        "When Seren woke, the river sounded happy again. Her horn shone steady. She learned something she would always keep. Kindness is not a race where you hurt yourself to win. Kindness is like breathing in and out. There is room for others and room for you.",
        "Years later, people said the birch leaves sometimes sounded like finch song. Children fell asleep easier there. And you, hearing this story, might feel a warm touch on the worried part of your heart, just long enough to fall asleep safe.",
      ], "Kindness is not a race you have to win at your own expense. Helping others works best when you rest, breathe, and are gentle with yourself too."),
      story("Liora and the Bridge of First Light", [
        "Between two lands that forgot to be friends, there was a very deep gorge. Clouds drifted through it like slow fish. The only way across was a bridge that looked like moonlight turned into wood. The railings felt like braided laughter.",
        "Unicorns guarded the bridge. They did not use swords. They used kind rules. Rule one: tell the truth about what you carry in your heart. Rule two: walk slow enough for your feelings to keep up. Rule three: say hello to the bridge before you step on, like you would knock at a friend’s door.",
        "Liora was the youngest unicorn guard. Her mane shifted through soft purple, sea green, and berry pink. She practiced saying hello to puddles. She bowed to spiders. She thanked rocks for not tripping her.",
        "One foggy morning a boy came. His cloak was too big. His bag clinked and smelled like bread. His boots were muddy. His eyes looked tired from worry.",
        "He said, I need to cross. Liora bowed her head. Tell the bridge your name, she said. Tell what you carry that is heavier than your bag. The boy swallowed. My name is Milo, he said. I carry a mistake. I told a lie. Someone felt hurt. I want to fix it.",
        "Liora’s horn felt warm. She was not judging. She was listening. The bridge likes fixing, she said. But it does not like running. If you run, the planks go thin. Milo nodded, but his legs wanted to hurry. They stepped on together. The fog under the bridge turned pale gold. You might picture that gold as brave feelings that still feel a little scared.",
        "Halfway across, Milo stopped. He whispered, What if they do not forgive me? Liora brushed his cloak with her shoulder. Forgiveness is not a thing you grab, she said. It is like a door someone opens inside. Your job is to knock in a kind way. The bridge will hold you while you knock.",
        "The bridge listened. The planks felt stronger. Milo breathed in for four and out for four, like his grandma taught him in storms. On the far side his bag felt lighter. The shame in his chest felt smaller too.",
        "People heard about Milo. More travelers came. A woman felt sorry for sharp words. A teacher worried he let a shy kid down. A musician could not find her voice. Liora greeted them all. Sometimes she walked with them. Sometimes she only stood guard while her horn glowed like a kind lighthouse.",
        "Not everyone crossed the first time. A merchant pretended he only carried silk. The bridge turned slippery until he laughed and said he also carried jealousy. Then the bridge forgave him.",
        "One evening the stars looked like sugar on dark cloth. Liora felt a pull in her chest. No traveler stood there. Only a question from her own childhood. The bridge shimmered. A soft voice asked, Liora, what do you carry?",
        "She almost said nothing. Then she remembered Milo. I carry fear, she said. I fear I will fail on a night someone really needs me. The bridge made a happy rumble. The planks lifted a little to meet her hooves.",
        "After that, her horn had a new kind of light. It was the light of saying, I am still learning. Travelers felt braver. Far away, a listener might touch her own chest and whisper, I am still learning too.",
        "Years went by. The two lands remembered to be neighbors. The bridge was easier to see in daylight. Liora grew up. On clear nights, people said you could cross alone if you were honest, slow, and polite.",
        "If you listened under the railings, you could hear a sound like someone tucking you in. First light does not always come from the sun. Sometimes it comes when you tell the truth about what you carry, and you keep walking anyway.",
      ], "Honesty softens hard paths. You cannot force forgiveness—you can only knock kindly and keep trying to make things right."),
      story("The Unicorn Choir of Silverpine", [
        "Silverpine Forest looked silver because the pine needles held moonlight. They saved the light bit by bit until the whole woods glowed soft. In the middle of the forest, a circle of unicorns did not rule anyone. They sang to help the land.",
        "They only met when the world’s music felt off. Not scary fixing. Kind fixing, like helping a shy note find its voice. The leader was old Caldera. His voice sounded like a low hum. His horn tip was chipped from tapping time on river rocks.",
        "On the night of this story, the choir met in a clearing. Mushrooms grew in neat rings. Fireflies warmed up their lights. But the sky’s music was wrong. Stars blinked out of beat. Owls forgot their songs. Crickets argued like a bad band.",
        "We need a new note, Caldera said. Not louder. Truer. Young Thistle lifted her head. What if we ask a human child to lend us a note? Humans were rare there. Their notes were bright and strong.",
        "Far away, a child brushed her teeth. She hummed a silly made-up song about a sock who wanted to be a hero. It was goofy. It was honest. Honesty helps true music.",
        "Thistle’s horn caught the edge of that hum. There, she whispered. The hum rode roots and cricket chirps and owl whispers until it reached the clearing like a happy gift.",
        "May we borrow it? Caldera asked the air. The unicorns lined up in a spiral. Youngest inside, oldest outside. Horns lifted like tuning forks.",
        "They started with quiet listening silence. Caldera tapped the oldest pine. A deep safe sound rolled out. Thistle added stream sparkle. Others added wind and hoofbeats and a deer deciding the world was still good. Last they wove in that sock-hero hum from far away. The sky seemed to smile.",
        "Stars found their beat again. Owls finished their songs. Crickets made up with duets. The child rinsed her toothbrush and felt cheerful for no clear reason. She did not know she helped. Real magic is often small and true, and far away the forest breathes easier.",
        "Borrowed notes should be thanked. At dawn Thistle walked moon paths to a house with a purple night light. She could not knock with hooves. She left a pine needle braided with her mane hair. It glowed a little.",
        "The next evening the child found the needle on her window sill. It smelled like winter and song. She put it in a jar by her bed. She dreamed of silver trees and calm unicorn faces. When she woke, her sock song sounded deeper, like the forest sang with her.",
        "Years later, when the forest went too quiet, the choir remembered that hum. They did not need to visit again. The note lived inside them. You are never too small to help the sky if you sing what is true, even about socks.",
        "Caldera tapped his horn one more time. Music filled the clearing. Rabbits stopped hopping to listen. The unicorns left, happy and full. Thistle looked toward the town where the child slept. Thank you, she whispered. The wind carried it.",
        "If a wood feels too quiet, hum something honest and a little silly. Listen to the needles. It might be unicorns. It might be your own braver voice. The tale says you already helped once. You can help again when stars need a friend.",
      ], "A small, honest song—even a silly one—can lift something bigger than you see. You never know when your truth helps the world sound kind again."),
      story("The River With Two Names", [
        "Maps show one name for a river. This river had two secret names. By day the people called it Quickribbon. It ran fast and bright over stones. By night the unicorns called it Softclock. Then the water sounded slow and patient.",
        "A unicorn named Bramble loved the night name best. When the moon was round, she stood in the water up to her knees. She listened to fish dreams and little stone wishes. She thought rivers keep secrets the way pillows keep whispers. They soften hard feelings until they feel safe.",
        "One summer the river felt sick. Not from poison. From noise. People built a mill. The wheel splashed too hard. Fish looked stressed. At night the river’s voice cracked. Bramble felt sad with the water.",
        "She visited the miller, Hester. Hester was tired, not mean. She had to make bread for three villages. The wheel had to spin. I cannot feed people with pretty sounds, Hester said. Bramble dipped her horn in a bucket of river water. The water glowed. Listen, Bramble said. Under the grind, a soft pulse still lived.",
        "They made a deal. At noon the wheel would rest one hour so the river could breathe. At night the wheel would stop so the river could heal. Each evening Bramble shared a thin slice of horn light so the mill could still finish its work. The light was warm, not burning.",
        "The first night Hester waited for failure. Instead the millstones glowed pink and purple. Flour fell like soft snow. Hester stared. That is useful magic, she said. Bramble laughed like kind bells.",
        "News spread. Kids skipped stones again. Fish came back, shy at first. You might think of your favorite song when the volume is finally just right.",
        "Then a storm threw branches into the wheel. The mill jammed. Hester reached to force it. Bramble stepped into the rain. Pushing too hard will break our fix, she said. Let me try something stronger than pushing.",
        "She spoke both river names out loud. Quickribbon, be quick where you must. Softclock, be slow where you heal. The water lifted the branches away, gentle as a hand brushing hair from a sleeping face. The wheel spun free. The storm rolled away, almost shy.",
        "Hester cried one quick tear. She put her hand on Bramble’s shoulder. Thank you for showing me strength is not always loud, she said. Bramble touched her palm with her horn tip like a promise.",
        "After that, noon felt gentle by the bank. Babies splashed while the wheel rested. At night people walked with lanterns and told the truth easier by the soft river sound.",
        "Bramble taught young unicorns to listen to one ripple from start to end. They wrote mud poems the river smoothed overnight. You might think of worries like water. Sometimes loud. Sometimes slow. Still moving if you let them.",
        "Years later, travelers said the river felt different at noon and midnight. Unicorns still waded under full moons. Kids still skipped stones. You could sleep knowing some problems have two sides, fast and slow, and both need kind words.",
        "If you stand by moving water, try two names. One for its job. One for its dream. Rivers and people both do better when someone listens to both.",
      ], "Most problems have a loud side and a quiet side. Patience and clear words help far more than force."),
      story("The Quilt of Many Colors", [
        "In a valley where mornings smelled like berries and evenings smelled like fresh bread, a unicorn named Oriole sewed quilts. She used thread, sunbeams, quiet after snow, and the laugh of someone who tries again after a fall. Her quilts were cozy famous, not flashy famous.",
        "Her big job was for the Great Sleep party on the longest night. Everyone brought one cloth square that stood for a hope. Oriole would sew them into one giant quilt for the town stage. Musicians played soft songs. Kids could stay up until they fell asleep on someone’s shoulder.",
        "One gray square worried her. A crow delivered it with a bow. The cloth had no name. No words. No pictures. Just soft gray, like a question.",
        "She put the gray square in the middle like the rules said. Other squares spread around it like petals. Gold stood for brave. Green for growing. Blue for calm. Pink for friends. The gray sat quiet. Oriole’s horn flickered. What hope is shy? she whispered.",
        "That night she dreamed of a child who colored outside the lines on purpose with a crayon marked maybe. The child laughed. Oriole woke with a warm idea. She sewed around the gray with thread made from listening at the market to worries, joys, small angers, big kindnesses.",
        "The gray square changed as she listened. It looked like dawn before it picks pink or orange, when anything can still happen. Neighbors peeked in. The baker brought a bread-shaped square. The teacher brought fingerprints. A shy child brought one star and a smudge.",
        "Oriole sewed in spirals. Her horn helped when her hooves got tired. The quilt grew heavy with love, like a warm cat on your lap. The gray middle still waited. Oriole saw the truth. The gray was not empty. It was space for people who do not know their hope yet.",
        "On the longest night, snow fell light and sweet. The town came. Kids wore pajamas under coats. Oriole spread the quilt. Everyone gasped in a good way. Colors moved. The gray middle shone like moon on water.",
        "Touch it gently, Oriole said. People put hands on the gray. Some closed their eyes. Some whispered wishes they never said out loud. You might imagine your own hand there. It is okay not to know everything yet.",
        "Something lovely happened. Maybe magic. Maybe just people sharing one blanket. The gray began to show soft pictures under each hand. A door opens. A bird comes home. A paper says try again in kind letters. Friends tie a bracelet. Each person saw something a little different. Each saw enough.",
        "At midnight wind rattled the shutters. The quilt corners lifted. Oriole’s horn glowed brighter. The quilt did not fly away. It pressed down like it grew roots. The wind gave up and turned into pine-smelling breeze. Kids slept to music. Grownups carried them home with quilt pictures in their minds.",
        "Later Oriole cut the big quilt into small ones for anyone who needed warmth in body or heart. Each gray patch was cut to fit that person. People say those quilts bring colorful dreams even after gray days.",
        "Oriole kept one strip where every color met. She stitched a tiny sleeping unicorn under a bright wandering star. Stories travel best when a kind listener takes them home.",
        "If tonight feels plain, remember: gray can be space. Listening can be thread. Morning is a color you and the world can pick together.",
      ], "It is okay not to know your hope yet. Space, listening, and time can turn uncertainty into something gentle and bright."),
    ],
    fantasy: [
      story("The Dragon Who Collected Lullabies", [
        "Past the Whispering Mountains lived a dragon named Aurelius—big as a barn, gentle as a folded blanket. His scales were deep evening blue; his belly, soft rose pink. Other dragons thought him odd, for he collected lullabies the way some people collect coins.",
        "He never stole songs. He traded. He thought a lullaby is a bridge from awake to asleep, and bridges should be fair. He visited towns with warm stones for cold feet, honey for sore throats, and little jokes on leaves for people who forgot how to giggle softly.",
        "One fall, people said a girl in the valley could not sleep. Not from monsters under the bed. Aurelius could talk to those. Her thoughts ran in circles like puppies chasing tails. Her name was Mara. Her mother sang until her voice hurt. Her father paced until his socks wore thin.",
        "Aurelius landed at the village edge. He never sat on roofs or laundry. He folded his wings. He tapped the mayor’s door with one claw. I hear you have a child who cannot sleep, he said in a low, kind rumble.",
        "The mayor led him to Mara’s house. Mara peeked from behind a chair. Aurelius sat on the garden path so he would not tower over her. May I trade? he asked. I give you a warm stone from my breath. It stays cozy till morning. You give me one line of a song you like, even if it sounds silly.",
        "Mara thought. The clock ticked. You might imagine giving a line too. Mara whispered, Like Twinkle Twinkle, but for cats. Aurelius smiled with his eyes. Perfect, he said. That is a seed.",
        "He did not sing yet. He told a story about a dragon scared of thunder until a mouse taught him to count booms. One boom, two booms, three booms, you are still here. Mara laughed once. Laughter is the first step toward sleep, Aurelius knew.",
        "For a week he came back each night with a new trade. Warm stone for a rhyme. Honey for a hum. A leaf joke for a deep breath. Bit by bit Mara’s own lullaby grew. It was not stolen. It was built from courage she already had. He kept each part in a jar that glowed like evening light.",
        "On the seventh night the village watched from a kind distance with blankets and cocoa. Aurelius lifted the jar. The light inside matched Mara’s slower breathing. He sang her whole lullaby, soft as snow on wool. Mara’s eyes closed. She smiled once. She slept. Her mother cried happy tears.",
        "Aurelius opened his wings. He bowed to Mara, which dragons hardly ever do. Thank you, he said. Your song will help others. Mara dreamed of blue scales, cinnamon smell, and thunder turned kind.",
        "News spread. Shepherds, weavers, even a duke who said he did not need songs—all got visits. Aurelius traded warmth for truth and never made people feel small. His jars filled a cave library. The cave echoed soft, never sharp.",
        "Years later, travelers said the mountains hummed at dusk like a cradle. Kids in three lands believed dragons could guard sleep. You might feel a warm jar-light in your chest, remembering that busy minds can still build a lullaby one true line at a time.",
        "If sleep is slow tonight, trade with yourself like Aurelius. Warm socks, tea, or a stuffed toy for one honest line of song. Kindness is real. A careful dragon lands softly.",
      ], "Peaceful sleep often comes in small trades with yourself—one cozy thing for one honest, gentle thought."),
      story("The Mapmaker of Second Chances", [
        "In a city full of bridges and bakeries lived a woman named Sable. She drew maps. Not treasure maps. Maps through shame and mistakes and I-wish-I-had-said-that-better. Her paper smelled like rain. Her ink colors mixed in soft ways.",
        "Her shop sat above stairs that squeaked hello. People climbed up, nervous. A boy who laughed when someone fell. A grandma who never sent a letter for forty years. A knight who forgot to feed his horse before a contest and could not forgive himself.",
        "Sable listened slowly, like bread rising. She asked three things. What happened? What do you wish happened? What small true step can you try tomorrow? She wrote answers on the table edge like signposts, not like judging.",
        "For the boy she drew three stops. Say sorry without excuses. Help someone up next time. Practice a joke that laughs with people, not at them. Embarrassment forest had a clearing that said people forget faster than you think. Pride river had a shallow spot that said say sorry anyway.",
        "For the grandma the map crossed years. Mountains named Regret. Valleys named Time. The path led to a meadow: mail the letter or read it aloud to a tree. Trees keep secrets, Sable said. Sometimes that is enough.",
        "For the knight the map looked silly on purpose. A cartoon horse talked. Steps: brush the horse, give an apple, whisper sorry to the mane. The knight laughed, then stood tall. I can do that, he said. Sable tapped his shoulder with her pen like a starting bell.",
        "You might think of a friend you miss or homework you skip. Start small, true, and kind, Sable would say. Maps do not skip walking. They help you walk.",
        "Some people crumpled their maps. Sable ironed the paper flat and drew again. One man framed his map and froze. Sable brought him bread. Looking is step zero, she said. Step one is one breath forward.",
        "One winter bridges froze. People got snappy. Sable opened free cider and maps with one line: share warmth. Kids drew paths house to house for cookies, jokes, sorry. The city warmed inside.",
        "Sable grew gray-haired like her compass. Her helper Jory used to be the laughing boy. His hands shook less. Do maps work? he asked. People work, Sable said. Maps remind them they have feet.",
        "Harder hurts came too. Sad doors. Hot anger. Sable drew twisty paths so people met themselves twice, mean once, gentle once. She drew a bench: sit until your shoulders loosen. You can borrow that bench in your mind.",
        "A whole class visited once. Sable drew a giant chalk map in the yard. Ask, listen, try again. Rain washed it away. Kids drew dragons and cupcakes anyway. Joy is part of healing, she said.",
        "On her last shop day she drew a map for herself. One word in the middle: rest. Paths to nap, tea, wind, and forgive yourself for not fixing everything. She hung it over her bed. The geese honked approval.",
        "Years later people sold copies of her maps without knowing her name. They still helped. You can draw a tiny map tonight too: one step, one truth, one kindness. Morning is a new place you can walk to.",
      ], "A map cannot walk for you—it only reminds you that your feet can take the next small, honest step."),
      story("Sir Rowan and the Armor of Quilted Stars", [
        "Sir Rowan wore armor that hardly clinked. Inside it was padded with quilt stars sewn by their aunt. Each star held a little courage for cold days. People joked until they saw Rowan lift a cart without squashing one strawberry. Rowan thought strength should be careful.",
        "Rowan’s task was not the usual kind. No stolen gold. No evil king. Rowan had to cross the Sullen Marsh. Gloomy lights there fed on sulking. Neighbors had stopped being kind. The mud held grudges. Boots stuck.",
        "At the edge Rowan met a frog in a tiny cape. Turn back, it croaked. The marsh likes sad company. Rowan knelt. I will bring better company, they said. They had tea cakes, a harmonica, and a list: sorry things I owe myself.",
        "The first mile was sticky mud and whiny thoughts like gnats. Rowan played harmonica badly on purpose. The gnats got confused. Little lights flickered closer. Rowan offered a tea cake to one. It could not eat, but it warmed up beside kindness. It sat on Rowan’s shoulder like a tiny lantern.",
        "Deeper in, voices sounded like friends being mean. Rowan gripped the sword, then let go. Those are not my friends, Rowan said. Those are echoes. Truth cut the fake voices like cobwebs. You can try that with worry: call it an echo, watch it fade.",
        "In the middle stood a reed throne. A sign said sit here if you want to be right forever. Rowan laughed. That sounds tiring, they said. They put a quilt star pillow on the throne and sat on the ground instead. They shared tea with the lights until the reeds relaxed.",
        "Water drained slowly over honest days. Neighbors came, pulled by music and cake smell. They argued, then laughed at how small the fight looked in sun. Rowan asked simple questions. What do you need? What can you give? What will you try tomorrow?",
        "By full moon the marsh was a wet meadow with fireflies. The frog’s cape fluttered proud. Mud stained Rowan’s armor. Their aunt would sing it clean. Rowan called that a win.",
        "Years later new knights asked for tips. Wear soft insides, Rowan said. Hard shells crack. Soft linings hold. A child tapped the armor; the quilt inside stayed fine.",
        "Rowan kept a notebook of small wins. A snail crossed because someone waited. A shy kid spoke in class. A baker said sorry and brought muffins. On hard nights Rowan read those pages. Brave does not always arrive with trumpets. Sometimes it comes with tea.",
        "When robbers scared a food cart, Rowan used a shield and a steady voice. The robbers were hungry, not monsters. Rowan shared food and wrote the mayor about fair prices. No one died. Rowan told students that is a song worth singing.",
        "One winter Rowan got sick with normal sick. Kids drew maps to Rowan’s door: hugs, soup, stories. Rowan visited each path, weak and glad. That is what a quest can become, Rowan would say: coming home to people who remember your kindness.",
        "So sleep with quilt stars if you have them, or with the idea of them. Your armor can be real kindness, soft inside, strong enough to help.",
      ], "True strength is careful: protect what matters without crushing what is fragile—including your own heart."),
      story("The Giant’s Teacup", [
        "In old tales giants are loud. Brion was only loud when he laughed. He covered his mouth with a hand like a wagon wheel because he lived near careful gardeners and he liked radishes. His home was a kind hill cave with tables from smooth fallen trees. His favorite thing was a huge teacup with violets painted on it.",
        "Brion felt lonely in a special way. He was gentle, but his big body scared people before they saw his face. Kids peeked from barns. Grownups whispered. Brion acted fine, but his cup rattled when he poured pretend tea for nobody.",
        "One morning a girl named Pella crossed a fence she should not cross. She chased a lamb. The lamb got stuck between Brion’s boot and a giant mushroom. Pella froze. Brion lifted his boot a tiny bit. Hello, small brave one, he whispered.",
        "Pella gulped. Hello, big careful one, she said. Brion laughed into his hand. The ground shook a little, kindly. The lamb ran free, baaing happy. Pella could have run. She asked, Do you drink tea? Brion’s eyes lit up. I pretend, he said. I need a friend to make it real.",
        "They built trust over three days. Day one: Pella brought herbs. Brion warmed water with soft breath. Day two: grandma sent honey. Brion had a shiny spoon like a shovel. Day three: they drank together. His sip was huge. Hers was a thimble on a saucer.",
        "Village people got curious. They brought apples, songs, and sorry for running away. Brion bowed to accept the sorry.",
        "A lord told Brion to leave. Brion packed his cup, sad. Pella stood on a stump. Her voice shook but it was true. He softens the ground if you ask, she said. He fixes roofs. He cries when lambs are lost. People shuffled. The lord huffed away.",
        "Brion stayed. He gardened with big gentle hands. Pella grew up. Birds nested in his beard with permission. You might smell mint steam and feel safe.",
        "Later, on Pella’s wedding day, Brion poured tea for everyone with a kind ladle. His violet cup sat in the middle. A child asked if giants dream. We dream of being seen, Brion said. Then we dream tea parties.",
        "Between those days were normal Tuesdays. Brion fixed fences. He taught a teen to lift a cart without a hurt back. He learned to write wobbly thank-you notes. Pella brought him books. He read aloud until cats purred three doors down.",
        "Lightning hit an oak. People thought they might blame Brion. Instead he stacked good wood for fires and planted acorns in neat rows. The town learned big and gentle can still be responsible. Kids played careful giants with bark shields.",
        "Brion is still there in the story, cup ready. If you feel too big or too small, remember Pella’s thimble tea. Love can fit both sides.",
        "Sleep like a tucked-in lamb. Brion’s laugh is far away, soft as bedtime thunder. The violets on his cup are brave hellos.",
      ], "Being truly seen—with kindness, not fear—is a home you can build anywhere, at any size."),
      story("The Library Under the Lake", [
        "Everyone knew the lake in Elderwyn was deep. Almost nobody knew it had a downstairs. Down there lived books on shelves like hard water. Pages rippled like small waves. The librarian was a turtle named Penta with glasses on a kelp string. Penta said bedtime stories matter most.",
        "Land people went down bubble stairs at dusk if they knocked three times on one dock post and promised not to drip on rare books. Kids crossed fingers behind their backs. Wet hair happens. Penta pretended not to see. Trust needs a little wiggle room.",
        "Caspar went down because reading felt hard. Letters jumped. He felt ashamed. He dreamed of drowning in paper, not water. His mom heard about the library from a baker who heard from a cat. Moms find ways.",
        "Caspar dripped in a room of glowing clams. Penta bowed tiny. Welcome, reader, Penta said. Caspar started, I am not— You came, Penta said. That counts.",
        "Penta gave him a book with empty pages. This book reads you first, Penta said. Caspar opened it. It showed kind clips of his own life: block towers, feeding a duck, moving his mouth slow around a word. A soft voice said, see how long you have learned.",
        "Caspar cried. Underwater you cannot see tears, but Penta gave a bubble hanky. Caspar laughed. Other kids peeked from the stacks and smiled. A mermaid rolled a cart with books labeled courage, patience, try again.",
        "For months Caspar came at dusk. Penta taught him to make friends with letters. Trace in sand. Sing the word. Draw the story, then read it. No magic fast fix. Only time without shame.",
        "One night Caspar read a whole page to little kids. His voice shook then settled. Bubbles clapped. Penta nodded, proud inside the shell. Caspar’s book was not blank anymore. It held his first chapter in ink that did not wash away.",
        "Later Caspar taught on land. He kept a shell on his desk. He told stuck students about the lake basement as proof they could learn. You can touch your own book and remember: slow and soft can still be smart.",
        "His room had lake-colored pillows. Big kids helped little kids for silly stickers that still meant a lot. Caspar hummed Penta’s song, off key but useful. Parents said kids slept better when shame lifted.",
        "Once a year he took teens to the real dock. Some saw bubble stairs. All felt braver about reading out loud. A hard word can be a puzzle in your mouth until it fits, he’d say.",
        "Penta still sorts star reflections. Fish come to story time. Frogs listen to poems. Knock the post at dusk and maybe stairs appear. Be honest. Let your hair get a little wet.",
        "Sleep. Your mind can be a quiet lake. Shelves wait under the surface. Morning is the next page.",
      ], "Learning at your own pace, without shame, is still real learning—and it lasts."),
    ],
    magic: [
      story("The Wandmaker’s Apprentice", [
        "In a shop that smelled like storms kept safe in jars, a girl named Mira swept glittery dust while her teacher Vesper shaped wands—not the kind that zap villains, but the kind that help people aim their own good wishes, like training wheels for the heart.",
        "Above the door it said: A wand is a promise you can hold. Mira said it while she swept. Six months in, she still could not touch a finished wand. She cleaned tools and sorted crystals. Some crystals only sparkled when nobody lied. That made long store lines funny.",
        "One rainy Tuesday a woman came. She could not speak up at work even when she knew what was right. Vesper asked three questions. Then Vesper pulled a plain wood stick. Mira, get the blue-bottle courage on shelf three, Vesper said. Mira’s hands shook. This was a test.",
        "Mira climbed the ladder safe and slow. She read labels twice. She brought the bottle. Hold the rod still, Vesper said. Warm light like honey poured in. The wand felt warm, not hot. Will it talk for me? the woman asked. Vesper smiled. It will remind you your voice is already there.",
        "Mira watched the woman practice in the yard, wand in pocket, chin lifting bit by bit. Birds went quiet. You might hug a pillow and pretend a wand whispers, your words count, even soft ones.",
        "That night pride poked Mira. She snuck back and grabbed a half-made rod. Make me special, she whispered. The wood stayed cold. She felt hot shame. The honesty crystals went dull. Vesper came, not mad, sad. What did you ask the wood? I asked it to make me special, Mira said.",
        "Vesper sat on the floor. Special is not an order. It is something you find. They sanded the rod smooth again. They said sorry to the tree wood out loud. They told the crystals true jokes until they shone. Mira cried one fast tear.",
        "For months Mira learned real craft. Listen to the wood lines. Match wand to person like slippers, snug not tight. She messed up in public twice. One wand was too strong for a kid who only wanted sleep help, so the wand sang lullabies sorry on its own. She cracked another rod by rushing. Vesper made her fix it with gold glue and time.",
        "Her first solo wand went to a boy scared of dogs after one nip. She used bendy willow. She tied in thread from her scarf: scared is okay, still try. The boy tapped the wand. Warmth spread. Like borrowed brave.",
        "Years later Mira ran the shop. Kids on trips held plain wood blocks. She told them about the night pride tricked her and sorry fixed it. Wands are tree teachers, she said.",
        "Quiet nights she traced the door words. She thought of every child who needed a gentle nudge. Your hands are wands too, she’d say. Promise gentle.",
        "Sleep, dream student. Smooth today’s bumps tomorrow. Shine today’s brave spots. The shop sleeps. Thunder jars snore. Honest crystals still wink: we see you, kind kid.",
      ], "Your voice was always yours; honesty and patience shape it into something you can trust."),
      story("The Book That Ate Only True Sentences", [
        "At Scholar’s Green a shop sign creaked. Inside sat a book with tiny neat teeth along the edge. Old Yael owned it. It eats sentences, she said. It keeps true ones. If you feed lies it pouts for weeks.",
        "Most people laughed and bought postcards. One wet day girl Lottie came with a crumpled school paper. My teacher wants a stronger voice, she said. Yael tapped the book. This helps if you are brave.",
        "Lottie read: In conclusion, the book was fine. Chomp. The line vanished. Try truer, Yael said.",
        "Lottie tried: I stayed up late because I cared. The book purred. The line stayed, soft gold. She tried: I am scared people will laugh if I say what I mean. The book hugged that line. Saying scared out loud is brave too.",
        "For an hour Lottie fed lines. Fake fancy lines got eaten. True lines stayed, even if clumsy. Her paper got shorter and stronger.",
        "At closing her draft was half the size and twice as real. Borrow the book, Yael said. Bring it back honest. Lottie dreamed of kind little teeth.",
        "At school she read aloud. Her voice wobbled then settled. The class leaned in. A boy thanked her for saying she gets scared. He felt less alone.",
        "Not every visitor was nice. A loud speaker fed big empty words. The book burped smoke until he left. Truth still matters, the book seemed to say.",
        "Later Lottie taught school. She kept a cardboard copy with no teeth. What would the hungry page keep? she asked stuck writers. The true parts, someone might answer.",
        "She wrote Yael about teen worries. The book’s teeth softened with age. Yael mailed teas: lavender calm, mint focus.",
        "Once the lights went out. Lottie read by candle. The book’s teeth looked like a smile in shadow. Fixing words can be love, she thought. Keep the healing parts. Keep the writer.",
        "At graduation kids gave flashy speeches. The book ate half until they named real details: Mara shared her lunch when I forgot mine. Groans, then grins. Small truth beats shiny fluff.",
        "Yael gave Lottie the real book with a note: feed it truth daily. Clean with tea steam. Be kind when you sharpen truth. Lottie locked it in class for brave Fridays.",
        "If you journal tonight, picture polite teeth. Let them chew away junk. Keep what feels right. Sleep easier for it.",
      ], "Clumsy truth beats shiny lies; keep the sentences that feel kind and real."),
      story("Starlight in a Jar", [
        "Ezra wore patched robes and a bag that clinked. People overlooked him. He put starlight in jars for kids scared of dark. Not to erase night. To make night a friend.",
        "Starlight is shy, he said. You ask. You wait. You use glass made with joy and lids kissed with lullabies. His jars looked plain until you dimmed the lamp. Then they glowed like good memories.",
        "One winter a town lost power in a storm. Candles died. Ezra skied in, red-cheeked. Free samples, he called. He gave a jar to a toddler. The jar felt a little warm, safe not hot.",
        "He taught big kids to build their own. Draw dot-stars on paper, tape inside, add a small light. Honest starlight. You could try on a rainy night.",
        "Day two, jars dimmed. Starlight rests too. Ezra played a game: tell one brave thing today, watch the jar wake. Kids said helped sister, told truth, tried math again, said sorry to a tree for kicking it. The jars pulsed soft.",
        "A grump said that is not magic. Ezra bowed. Good, he said. It is practice with sparkle. The grump laughed. His jar flared.",
        "Power returned. Folks kept jars on sills. Ezra traveled to sick beds. He charged rich people extra so poor people got jars free.",
        "Ezra grew old. His hands shook for glass work. He taught students: starlight in a jar is a story and also real. On his last night friends told tales beside an open jar. Light gathered with no glass. He smiled. It was listening all along, he said.",
        "He rolled a cart of jars with a soft bell. He helped kids bottle moments: warm bread shared, your name said kindly. Tell the memory out loud and the jar refills.",
        "One child feared far cold stars. Ezra had her draw dot animals in the sky with silly names. Night turned into a game. You can rename a star tonight for fun.",
        "Hospitals wanted quiet glow jars. Families breathed easier. Ezra told jokes and tightened lids. Light means you may rest while the world spins, he said.",
        "Years later many kids slept near glowing jars. Parents said Ezra’s name soft. You might peek in your dark corner: a star kept you a seat.",
        "Sleep with or without a jar. Night is a blanket, not a monster. If you need light, ask inside yourself. Breath and story can bottle it.",
      ], "Courage can live in simple memories and brave little habits—night becomes gentler when you remember the light you already carry."),
      story("The Door That Opened to Yesterday’s Courage", [
        "In a dusty attic stood a blue door with no wall behind it. People thought it was pretend. Sol knew it was not. Sol was twelve and sneezy but brave with doors.",
        "One night Sol said something mean to a friend and saw hurt on their face. Sol could not sleep. Sol climbed up with a flashlight and touched the blue paint. The knob turned. A hall of mirrors waited. Each mirror showed an old time Sol was brave: bike scrapes and still smiling, helping a new kid, telling a teacher the truth, patting a crying sibling. The hall whispered, you are more than one bad minute.",
        "At the end sat older Sol with tea. I cannot fix tonight, older Sol said. I can show you fixes exist. The tea tasted like mint and okay-you-may-try.",
        "Sol cried, said sorry to the air, practiced words for tomorrow. Older Sol listened. Older Sol pressed a blue chip into Sol’s hand. Proof halls are real, they said.",
        "Morning came. No chip, but the words stayed. At lunch Sol found the friend, said true sorry, listened. The friendship wobbled then grew.",
        "The door showed new things on other nights. Future Sol laughing and trying. Quick kind peeks at other people’s brave halls. Sol always knocked first.",
        "Sol kept a notebook: blue for brave, green for fix-it, gold for party. On hard days Sol traced the colors until breath slowed.",
        "A scared friend came once. Sol skipped speeches. They sat on the steps and named good memories: you shared lunch, you told the truth about the vase, you made your sister laugh after tears. The friend walked away lighter. No magic door needed.",
        "Each spring Sol painted the frame fresh blue. Doors need care like stories about you, Sol told little cousins. Sol saved paint chips like layers of courage.",
        "College stress almost made Sol forget. One dream brought the hall back. Sol woke and stuck three true memories on the laptop. Tiny spell that works again and again.",
        "You do not need an attic. Memory can be a hall. Pick three kind brave honest moments before sleep. Sip them like tea.",
        "Years later Sol told nieces this tale. New owners of the house saw a soft blue glow at night, friendly not spooky.",
        "Close your eyes. Turn an imaginary knob. Walk past mirrors that like you. Drink tea with tomorrow-you who says try again. Then sleep. You earned it.",
      ], "One mistake does not erase who you are; you can say sorry, remember your brave moments, and begin again."),
      story("The Potion Master’s Worst Monday", [
        "Professor Maris owned hundreds of bottles in a tall tower. Some round, some tall. She made sleep brews and calm brews, but her favorite mixes helped people say sorry in a human voice or remember a friend’s favorite color.",
        "This Monday a flask fell. Spark steam turned every sock mismatched on purpose. Maris smiled. Mondays joke. Then an owl brought a letter. The queen’s niece could not stop worrying about what if. The queen wanted a sureness potion.",
        "Maris read the letter. Sureness is not juice in a cup, she thought. It is a habit you grow. She wrote back: send the girl for tea tomorrow, not potion. Still she mixed things in the pot because worry likes motion. Flowers, sugar, questions, a feather from a bird that flew far and came home.",
        "The pot burped rainbows. Not helpful. She tried starlight from a jar. Only the top sparkled while the worry still boiled. She laughed at herself. Even teachers grab shortcuts.",
        "That evening Priya came early, eyes darting. Cake first, Maris said. Sweet before big talks. Priya eased. Tea tasted like warm socks. I cannot bottle certainty, Maris said. I can give tools.",
        "They made a worry jar. Write each worry on paper, fold it, drop it in. Maris added a sip of brew so by morning paper turned to soft petals. They shrink when you name them, Maris said. You can use a box or doodle instead.",
        "They breathed slow like waves. Maris made goofy wave noises. They picked one small step for one worry. Priya’s shoulders dropped. Still scared, she whispered. Brave can be scared with shoes on, Maris said.",
        "Morning petals smelled sweet. Priya laughed. The queen offered gold. Maris asked for a calm corner in the market instead. Free teas labeled Monday, Tuesday, with real herbs and tiny jokes.",
        "Maris held potion picnics. Kids mixed berry mint honey water and named drinks after feelings. Parents watched feelings turn into recipes. Spills became giggles.",
        "Stressed guards got silly fizzy drinks until hiccups turned to laughs. The city slept better. Maris called it a win.",
        "She pinned kid thank-you notes on the wall. Your tea unclenched my tummy, one said. On gray days she read them for herself too.",
        "Years later Priya visited to learn listening, not measuring. Maris retired with proud odd socks. A note on the tower said bad Mondays teach if you let them.",
        "Sleep. If Monday waits past your eyelids, pick a jar, a breath, a memory hall, a star. You are slow good magic, even on Mondays.",
      ], "You can be brave and still feel worried; small steps and honest naming are stronger than fake certainty."),
    ],
    fairies: [
      story("The Thimble Tea Company", [
        "If you see a thimble cup steaming on your sill, thank the fairies. They run a tiny tea company. They bring courage sips before hard days. Boss fairy Tink loves kindness more than rules.",
        "Tink wore a rose-petal vest and a leaf clipboard. One spring day cherry petals flew like snow. An urgent order came: a child had a big day, music, math, a friend to fix things with. Her brave felt holey like a sock.",
        "Fairies do not shove tea into people. That is rude. They nudge. Dewdrop polished the sill. Mosslet made a rug so paint would not scratch. Sparkler added extra giggles.",
        "The mix had grandma memory, best-friend jokes, and I-can-try herbs from cliffs where someone said sorry first. The kettle sang a note only sleepy dogs usually hear.",
        "She found the cup while tying shoes. Mom thought a neighbor left it. Neighbors thought mom did. Only she tasted the real story: warm, sweet, cinnamon brave. She drank half, saved half.",
        "A tiny shine stayed on her lips in the mirror, just for her. Walking to school she breathed with the sidewalk cracks like a calm game the fairies started.",
        "At lunch a friend sat alone. She remembered saved brave in her thermos, pretend tea but real care. She sat, shared chips, shared quiet, shared a squirrel joke.",
        "The music show was not perfect, but human. Her hands shook then settled. Math needed one deep breath. She used words she practiced like a song for the friend fight. Magic did not erase work. Magic said work matters.",
        "Tink watched from a ceiling beam no principal sees. Check mark on the leaf. Young fairies learned: tea is a story until someone needs the story to be real.",
        "Hard days got ginger tea for shaky hands, chamomile for hot tears, mint for racing thoughts. Notes said: sit with you, not fix you. People felt warm chest hugs with no cup in sight.",
        "Sometimes wind tipped a cup. Fairies cried glitter, cleaned up, tried again. If a kid skipped the tea, fairies left a cookie backup.",
        "Grownups later swore thimble cups appeared before big talks. Tink retired in a peony. Pip took over and loved lists and hugs.",
        "No cup tonight? Picture one. Hot water steam. Notice yourself. Notice brave. Sip.",
        "Sleep. The tea shop is closed, but the recipe lives in your breath and tomorrow.",
      ], "Tiny acts of care—noticed breath, a shared snack, a kind word—turn courage into something you can really feel."),
      story("Willow’s Dew Architects", [
        "Willow was a fairy builder. She did not stack stone. She placed dew. Each dawn she drew plans on spider silk so sun could paint rainbows on ceilings that needed cheer. Her team used patience for a ruler.",
        "One hot August dew hid. Webs dried. Kids woke cranky and did not know why. Willow held a meeting on a dandelion. Ideas?",
        "Snail said go slow. Bee said work together. Ant said carry one drop at a time. Willow mixed the ideas. Early risers breathed on grass until tiny beads formed.",
        "One child slept through most of it but breathed slow in a dream. Fairies steered one wisp to her window. She woke to one rainbow stripe on the ceiling and smiled.",
        "More fairies came to learn. Care can look like design, Willow said. One dew dot can make a web look like jewels for a sad person. Splash wrong and a moth slips. Measure twice, bless once.",
        "Night school taught mist math: angle the grass so light hits the ceiling not the eyes. Enough dew for bees, not too much for ants. Sorry, clover, when students messed up.",
        "Lawnmowers annoyed everyone. Willow asked hedgehogs to trim edges Friday night so Saturday could sleep in. Neat for people, wild for bugs.",
        "One fairy wanted glitter dew every day. Willow said glitter blinds. Rainbows teach. Birthdays got sparkle. Tuesdays got plain honest drops.",
        "Winter meant frost art on windows in star shapes. Kids drew with warm fingers and watched melt trails. Pretty because it passes.",
        "Spring brought First Droplet Day. Willow stretched a teaching web over the well. One dew bead slid the silk and splashed sun stories on stone. Ordinary water can rainbow if it hangs brave, Willow said.",
        "Dawn walks taught quiet. Hush is building stuff, Willow said. Robins landed on students who held still. Graduation needed one new web blessing, no copycats. Tears happened. Leaf hankies waited.",
        "Hail threatened a spider web once. Willow’s team beat wings together until wind moved. The spider sent a fog-breath thank-you card. Willow hung it in mist.",
        "Years softened Willow’s wings. She wrote Dew for Kind Starters. Listeners feel that book in gentle mornings without knowing the title.",
        "Willow stepped down. A shy frog took the job. Frogs get dew. The meadow clapped in rustles.",
        "Her manual’s last line: be gentle with morning. Soft voice, slow stretch, crack the window for one outside breath. Dew notices.",
        "See a web tonight? Maybe Willow visited. Sleep under mystery rainbows. Thank the builders in dreams.",
      ], "Patience and gentle attention build beauty that makes the morning kinder for everyone."),
      story("The Promise of the Firefly Court", [
        "Deep in the lilac hedge at nine when parents call kids home, fireflies hold court. They do not judge people for fun. They watch promises: which glow, which flicker, which need help.",
        "Queen Gleam sat on braided grass. Her crown was a ring of light. Young firefly Fenn wanted a job guarding maybe-promises.",
        "Fenn’s test: follow one child one week, invisible, no meddling. The child was Clara, picked from a tulip hat.",
        "Monday Clara practiced piano, grumpy then glad. Keep, Fenn noted. Tuesday fed fish, quick but done. Wednesday kept a secret, lips zipped. Thursday cleaned room halfway, honest try. Friday snapped at a sibling, then sorry, then fixed. Fenn glowed proud.",
        "Saturday screen-time rules slipped. Sunday she reset with self-sorry. Fenn learned self-promises can stretch if you forgive and tighten.",
        "Sunday court met. Lights showed the week, no yelling. Verdict? the queen asked. Humans practice, Fenn said. Help practice, do not demand perfect. Promotion yes.",
        "Crickets cheered. New label: Promise Still Learning, softer glow. Fairies blinked at windows: try again, we see you.",
        "Clara saw three blinks from one bug and laughed. Three blinks meant we are proud. She slept easier.",
        "Later cases included scared promises, kid promises grownups forgot, hard days when getting up was the win. Labels added: learning, paused, talk again. Fair should feel like a blanket.",
        "Fireflies made blink codes: two for help please, four for I wait with you. Hedges looked like summer chat.",
        "Winter court sat in a log lit by saved summer light in acorn jars. Sick days and sad days got dimmer glow on purpose, kind not punish.",
        "Birthday week extra fireflies danced her name once, shy and sweet. Pollen made her sneeze and laugh.",
        "Fenn invented Promise Amnesty Hour to drop a vow that no longer fits, like outgrown shoes. Honesty grew. Blinks slowed, happy.",
        "Years from now one firefly might make you wonder. Wondering counts.",
        "Courts copied the idea in other hedges. Poets wrote truer vows. Friends answered messages because a warm nudge stirred them.",
        "Queen Gleam gave Fenn the crown with kinder blink rules. The hedge grew thick and sweet between rush and rest.",
        "Sleep. Broke a promise? Patch a corner tomorrow. The light is a nightlight for trying again, not a judge stare.",
      ], "Promises are practiced, not perfect—say sorry, adjust, and try again with a softer light."),
      story("Moss and Midnight", [
        "Fairy midnight is blue and moss green. Mushrooms jot notes. Roots whisper slow. Juniper guarded the line between neat lawns and wild grass so both sides stayed kind in memory.",
        "People feared pranks. Fairies feared boots. Juniper spoke both languages. A new tall fence scared a dog owner because the dog dug holes. Fairies saw a wall. Juniper called a toadstool meeting.",
        "Dog came with a kid who sometimes saw fairies. Fairies wore thistle vests. They argued like gnats, then calmed. Deal: move glow worms off the dog path, dog stops digging fairy food holes, kid keeps the water bowl full.",
        "Fence stayed but got tiny blue fairy doors. People rolled eyes kindly. You might feel softer blocks when someone listens, even if you never spot a door.",
        "Hardest job: lonely elder inside. Fairies thought they did not care. Juniper wrote welcome in moss on the patio. The elder touched it; it felt warm. First yard step in months. Tea thimble appeared. Words were not needed first.",
        "Big kids staring at ceilings got extra window fireflies: finish the chapter, drink water, tell your brain tomorrow is for trying. No shame, only invites.",
        "A road plan threatened the hedge. Frogs croaked in rhythm like fake traffic counts until humans filed slower safer papers.",
        "Kids drew crayon fairy gates and hid them in trees. Juniper pinned them on the office wall. Your paper gate counts too.",
        "Two fairy families fought over mushrooms. Juniper made them swap houses one day. Sticky empathy beat rules. They swapped recipes and stopped sulking.",
        "Juniper’s notebook listed tiny peaces: snail helped, rose not stepped on, kid art on bark. Bad nights, read the list by glowworm light. Borders are pauses, not weapons, she wrote.",
        "A kind child’s name went in the book when she watered a thirsty street tree with nobody watching. Quiet kindness counts loud.",
        "Summer shadow puppets on tents showed kind dragons and sorry heroes for scared campers. Crickets carried laughs.",
        "Storms flooded fairy basements. Leaf umbrellas, dandelion high ground, tiny lantern grief boats, then mud rebuild together.",
        "Juniper grew moss on her wings like wisdom. She trained beetle, mouse, teen headphone fairy who still listened deep. Fences turned more into hedges with gaps.",
        "When Juniper napped under a log forever, the world dimmed a breath, then brightened with stories. You can touch moss and think welcome.",
        "Sleep in blue midnight. Moss hugs you like roots hug trees. Fences can have doors. Hearts can too.",
      ], "Listening turns walls into bridges; quiet kindness can change what looked stuck."),
      story("The Acorn Orchestra", [
        "Each fall fairies tuned the woods. They hollowed acorns into flutes. They practiced for the Great Rustle when first big wind comes so leaves fall in tune, at least to fairy ears.",
        "Maple stood on a stump with a twig baton. Squirrels drummed. Beetles played low notes. Finches trilled. Frogs crooned. Owls sometimes gave unwanted tips.",
        "Shy mouse Pip dropped a flute in leaves before a solo. Squeak panic. Maple stopped. Improvise, Maple said. Pip tapped nuts, clicked seeds, whistled through teeth, messy and true. The woods leaned in.",
        "You might hear leaf rustle on the way home and feel your shoulders drop. That counts as music.",
        "Rehearsals fought sometimes. Fast squirrel, mad finch, cookie break until calm. Art is breathing together, Maple said. Pip wrote that on a leaf program.",
        "A human kid played violin with them once, not to steal the show, to listen better. Parents cried. Fairies cried sparkles.",
        "After shows Maple held listen circles, no instruments, just breath and story. A child could share a time music made her brave. Those memories became next year’s seeds.",
        "Winter almost canceled practice. Frost broke flutes. Squirrels shared nuts for time. Beetles carved bark whistles. Quieter show, still beautiful.",
        "Maple taught school kids rhythm by walking: left, right, breathe, listen. You can march under covers and giggle. Music starts in bodies.",
        "Old acorn flutes rested in a hall of honor. New players touched them for luck and promised gentle play. Maple’s smooth twig slept beside them.",
        "Under your window you might hear leaf scrape leaf, frog warm-up, heart beat. Secret encore for almost-sleepers.",
        "People rarely saw the Great Rustle. They felt a day when leaves danced instead of scratched. Raking felt easier. Kids jumped piles. Maple bowed on the stump.",
        "Someone wanted to pave part of the wood. Maple sang a lullaby so sweet the planner remembered fort-building as a kid. Plans changed a little. Fairies take small wins.",
        "Years later offices played bird-and-wind tapes to relax. Maple got paid in berries. Pip got fan mail on seeds.",
        "Maple retired. A crow took the baton, strict and shiny. Beatbox drums joined, weird then loved.",
        "Listen tonight: far rustle, branch tap, breath like song if you let it.",
        "Close your eyes. This concert is yours. Leaves fall soft. Dreams float like notes. Morning claps when you are ready.",
      ], "Messy, honest music made together beats perfect silence—listen, breathe, and let everyone find their note."),
    ],
  };
})();
